dxc-technology/halstack-angular

angular.json
package.json
projects/dxc-ngx-cdk-examples/src/app/components.ts
projects/dxc-ngx-cdk-examples/tsconfig.app.json
projects/dxc-ngx-cdk-examples/tsconfig.spec.json

Site working on the cdk as well as example pages

Fixed site and example pages

---

projects/dxc-ngx-cdk-site/src/app/app-routing.module.ts
projects/dxc-ngx-cdk-site/src/app/app.module.ts
projects/dxc-ngx-cdk-site/src/app/components/dynamic-component/dynamic.module.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-basic/chip-basic.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-basic/chip-basic.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-border/chip-border.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-border/chip-border.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-coloured/chip-coloured.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-coloured/chip-coloured.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-disabled/chip-disabled.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-disabled/chip-disabled.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-example/chip-example.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-example/chip-example.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-import/chip-import.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-import/chip-import.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/properties/box-table-properties/chip-table-properties.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/properties/box-table-properties/chip-table-properties.component.ts
projects/dxc-ngx-cdk-site/src/app/pages/chip/chip.component.html
projects/dxc-ngx-cdk-site/src/app/pages/chip/chip.component.ts
projects/dxc-ngx-cdk-site/src/app/pages/chip/chip.module.ts
projects/dxc-ngx-cdk-site/src/app/pages/components-sidenav/components-sidenav-menu/components-sidenav-menu.component.html
projects/dxc-ngx-cdk/src/lib/dxc-chip/dxc-chip.component.html
projects/dxc-ngx-cdk/src/lib/dxc-chip/dxc-chip.component.spec.ts
projects/dxc-ngx-cdk/src/lib/dxc-chip/dxc-chip.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-chip/dxc-chip.module.ts
projects/dxc-ngx-cdk/src/public-api.ts

Adding chipcomponent

---

projects/dxc-ngx-cdk-site/src/app/components/examples/box/box-theme/box-theme.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/chip/chip-theme/chip-theme.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/link/link-theme/link-theme.component.html
projects/dxc-ngx-cdk-site/src/app/pages/chip/chip.module.ts

Titles changed from "Tokens" to "Theming" and added color previews to Chip component.

Theming table improvements

---

projects/dxc-ngx-cdk/src/lib/dxc-select/dxc-select.component.html
projects/dxc-ngx-cdk/src/lib/dxc-select/dxc-select.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-text-input/dxc-input-text.component.html
projects/dxc-ngx-cdk/src/lib/dxc-text-input/dxc-input-text.component.ts

Select opens with up and down keyboard.
Input text prefix and suffix not longer tabbable.

Keyboard support for select and input

---

projects/dxc-ngx-cdk-site/src/app/components/examples/footer/footer-theme/footer-theme.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/footer/properties/footer-table-properties/footer-table-properties.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/header/header-theme/header-theme.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/header/properties/header-table-properties/header-table-properties.component.html
projects/dxc-ngx-cdk/src/lib/dxc-footer/README.md
projects/dxc-ngx-cdk/src/lib/dxc-footer/dxc-footer.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-header/README.md
projects/dxc-ngx-cdk/src/lib/dxc-header/dxc-header.component.ts
projects/dxc-ngx-cdk/src/lib/theme/defaultTheme.ts
projects/dxc-ngx-cdk/src/lib/theme/theme.directive.ts

Thematizable logos for header and footer components.

Mparrilla logos

---

projects/dxc-ngx-cdk-site/src/app/components/examples/button/button-modes/button-modes.component.html

Added mode prop to example in the site

Fix mode button

---

projects/dxc-ngx-cdk/src/lib/dxc-application-layout/dxc-application-layout-sidenav/dxc-application-layout-sidenav.component.ts

removing arrowDistance prop from DxcApplicationLayoutSidenav

removing arrowDistance prop

---

projects/dxc-ngx-cdk-examples/src/app/pages/wizard/wizard.component.html
projects/dxc-ngx-cdk-examples/src/app/pages/wizard/wizard.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/wizard/properties/wizard-table-properties/wizard-table-properties.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/wizard/wizard-api/wizard-api.component.html
projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard-icon/dxc-wizard-icon.component.html
projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard-icon/dxc-wizard-icon.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard-step/dxc-wizard-step.component.html
projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard-step/dxc-wizard-step.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard.component.html
projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard.component.spec.ts
projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard.module.ts
projects/dxc-ngx-cdk/src/lib/dxc-wizard/services/wizard.service.ts
projects/dxc-ngx-cdk/src/public-api.ts

Wizard component now accepts DxcWizardStep as child, and steps accept DxcWizardIcon as child.

Wizard component with steps and icons

---

projects/dxc-ngx-cdk-examples/src/app/pages/paginator/paginator.component.ts
projects/dxc-ngx-cdk-examples/src/app/pages/resultset-table/resultset-table.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/paginator/properties/paginator-table-properties/paginator-table-properties.component.html
projects/dxc-ngx-cdk/src/lib/dxc-paginator/dxc-paginator.component.html
projects/dxc-ngx-cdk/src/lib/dxc-paginator/dxc-paginator.component.spec.ts
projects/dxc-ngx-cdk/src/lib/dxc-paginator/dxc-paginator.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-resultable/table.ts

changing itemsPerPageOptions from object[] to number[].

changing itemsPerPageOptions

---

projects/dxc-ngx-cdk-examples/src/app/pages/wizard/wizard.component.html
projects/dxc-ngx-cdk/src/lib/dxc-wizard/dxc-wizard-step/dxc-wizard-step.component.ts
projects/dxc-ngx-cdk/src/lib/theme/defaultTheme.ts

Fixes in the Wizard component style colors.

Fixed disabled wizard styles

---

projects/dxc-ngx-cdk-examples/src/app/pages/standard/application-info.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/resultset-table/properties/resultset-table-properties/resultset-table-properties.component.html
projects/dxc-ngx-cdk/src/lib/dxc-application-layout/dxc-application-layout-footer/dxc-application-layout-footer.component.scss
projects/dxc-ngx-cdk/src/lib/dxc-application-layout/dxc-application-layout-footer/dxc-application-layout-footer.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-application-layout/dxc-application-layout.component.ts

apllication layout style fix + resultTable documentation

apllication layout style fix + resultTable doc

---

projects/dxc-ngx-cdk-site/src/app/components/code-playground/code-playground.component.scss
projects/dxc-ngx-cdk-site/src/app/components/examples/overview/overview-themes/overview-themes-theme-ts.properties
projects/dxc-ngx-cdk/src/lib/dxc-application-layout/dxc-application-layout-sidenav/dxc-application-layout-sidenav.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-table/dxc-table.component.ts
projects/dxc-ngx-cdk/src/lib/theme/complexThemeBindingStrategy.ts
projects/dxc-ngx-cdk/src/lib/theme/componentTokens.ts

- Changed names functions complex theme
- Higher height for monaco-editor
- Updated example theme object with comments
- Added overflow x to table + new tokens for scrollbar
- Removed focus from arrow sidenav

Documentation theme

---

projects/dxc-ngx-cdk/src/lib/dxc-button/dxc-button.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-paginator/dxc-paginator.component.scss
projects/dxc-ngx-cdk/src/lib/dxc-paginator/dxc-paginator.component.ts

Fixed disabled outlined button and disabled button in paginator

Fixed disabled outlined button and disabled button in paginator

---

projects/dxc-ngx-cdk/src/lib/dxc-chip/dxc-chip.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-date/dxc-date.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-progressbar/dxc-progressbar.component.scss
projects/dxc-ngx-cdk/src/lib/dxc-text-input/dxc-input-text.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-textarea/dxc-textarea.component.html
projects/dxc-ngx-cdk/src/lib/dxc-textarea/dxc-textarea.component.ts
projects/dxc-ngx-cdk/src/lib/theme/componentTokens.ts

- Fixed bug invalid and focus colors from input
- Removed focus from chip
- Added focus to calendar icon from date
- Fixed bug tokens progressBar
- Fixed bug tokens invalid and required textarea

Fix bugs colors

---

projects/dxc-ngx-cdk/src/lib/dxc-text-input/dxc-input-text.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-textarea/dxc-textarea.component.ts

Fixed #316 
Also fixed focus color in textarea component and token for font color in underline in input component.

Fixed font family on input component and textarea

---

projects/dxc-ngx-cdk/src/lib/dxc-file-input/dxc-file-input.component.spec.ts
projects/dxc-ngx-cdk/src/lib/dxc-file-input/dxc-file-input.component.ts
projects/dxc-ngx-cdk/src/lib/dxc-file-input/services/files.services.ts

- Fixed when no multiple, file should override the one already selected.

[Patch] Fixed one single file in file input

---

projects/dxc-ngx-cdk/src/lib/theme/componentTokens.ts

Changed the font-size of the table component to set it to 0.875rem (14px).

[Patch] Table font-size changed

---

projects/dxc-ngx-cdk/src/lib/dxc-select/dxc-select-option/dxc-select-option.component.html
projects/dxc-ngx-cdk/src/lib/dxc-select/dxc-select-option/dxc-select-option.component.ts
projects/dxc-ngx-cdk/src/lib/theme/componentTokens.ts

- Changed tick size from 18x18px to 16x16px.
- Added missing token for tick color.

[Patch] Select: Change size tick selected #525

---

projects/dxc-ngx-cdk/src/lib/dxc-paginator/dxc-paginator.component.ts

Types for Paginator component

---

projects/dxc-ngx-cdk/src/lib/dxc-checkbox/dxc-checkbox.component.ts

Types for Checkbox component

---

projects/dxc-ngx-cdk/src/lib/dxc-alert/dxc-alert.component.ts

Types for Alert component

---

projects/dxc-ngx-cdk/src/lib/dxc-radio/dxc-radio.component.html
projects/dxc-ngx-cdk/src/lib/dxc-radio/dxc-radio.component.ts

Types for Radio component

---

projects/dxc-ngx-cdk/src/lib/dxc-table/dxc-table.component.ts

[Patch] Horizontal scroll in table component

---

projects/dxc-ngx-cdk-site/src/app/pages/theme-builder/themes/AdvancedTheme.json
projects/dxc-ngx-cdk-site/src/app/pages/theme-builder/themes/DefaultTheme.json
projects/dxc-ngx-cdk-site/src/app/pages/theme-builder/themes/schemas/Advanced.schema.json
projects/dxc-ngx-cdk-site/src/assets/styles/themesProperties.ts
projects/dxc-ngx-cdk/src/lib/dxc-checkbox/dxc-checkbox.component.ts
projects/dxc-ngx-cdk/src/lib/theme/complexThemeBindingStrategy.ts
projects/dxc-ngx-cdk/src/lib/theme/componentTokens.ts
projects/dxc-ngx-cdk/src/lib/theme/test/AdvancedTheme.json

- Renamed tokens.
- Updated styling.

[Major] Updated component specs in checkbox component

---

package-lock.json
projects/dxc-ngx-cdk-site/src/app/app-routing.module.ts
projects/dxc-ngx-cdk-site/src/app/app.module.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/radio-group/properties/radio-group-properties/radio-group-properties.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/radio-group/properties/radio-group-properties/radio-group-properties.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/radio-group/radio-group-api/radio-group-api.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/radio-group/radio-group-api/radio-group-api.component.ts
projects/dxc-ngx-cdk-site/src/app/components/examples/radio-group/radio-group-import/radio-group-import.component.html
projects/dxc-ngx-cdk-site/src/app/components/examples/radio-group/radio-group-import/radio-group-import.component.ts
projects/dxc-ngx-cdk-site/src/app/pages/components-sidenav/components-sidenav-menu/components-sidenav-menu.component.html
projects/dxc-ngx-cdk-site/src/app/pages/radio-group/radio-group.component.html
projects/dxc-ngx-cdk-site/src/app/pages/radio-group/radio-group.component.ts
projects/dxc-ngx-cdk-site/src/app/pages/radio-group/radio-group.module.ts
projects/dxc-ngx-cdk/package-lock.json
projects/dxc-ngx-cdk/src/lib/dxc-radio-group/dxc-radio-group.component.html
projects/dxc-ngx-cdk/src/lib/dxc-radio-group/dxc-radio-group.component.ts

Adding props table and import module section

Adding site page for radio group

---

projects/dxc-ngx-cdk-site/src/app/components/examples/textarea/textarea-properties/textarea-properties.component.html
projects/dxc-ngx-cdk-site/src/app/pages/theme-builder/previews/textarea-preview/textarea-preview.component.html
projects/dxc-ngx-cdk/src/lib/dxc-textarea/dxc-textarea.component.spec.ts
projects/dxc-ngx-cdk/src/lib/dxc-textarea/dxc-textarea.component.ts

Adding new defaultValue property, test and documentation

[Minor] Adding defaultValue to textarea

---

projects/dxc-ngx-cdk/src/lib/dxc-date-input/dxc-date-input.component.ts
projects/dxc-ngx-cdk/src/lib/utils/date-functions.ts

This reverts commit e16d715ce2f0737af06e22e66249a88c7399c5ae.

Revert "Changed import dayjs"
